# Generated by Django 5.0.7 on 2025-09-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicel',
            new_name='Vehicle',
        ),
    ]
