# Generated by Django 5.0.7 on 2025-10-12 18:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_vehicel_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lesson_type', models.CharField(choices=[('theory', 'نظري'), ('practice', 'عملي')], default='theory', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default='10:00')),
                ('duration', models.IntegerField(default=60, help_text='المدة بالدقائق')),
                ('status', models.CharField(choices=[('upcoming', 'قادم'), ('completed', 'مكتمل'), ('canceled', 'ملغى')], default='upcoming', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.student')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
        ),
    ]
